In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [29]:
df = pd.read_csv('sample_test.csv')
df

,Lv0,Lv1,Lv2,Lv3,Lv4,LvPK,LvPK_2,Size
0,1.220000e+11,1.170000e+11,1.170000e+11,1.170000e+11,1.110000e+11,90,9,198
1,1.220000e+11,1.170000e+11,1.170000e+11,1.170000e+11,1.120000e+11,31,3,17488
2,1.220000e+11,1.170000e+11,1.170000e+11,1.230000e+11,1.120000e+12,90,9,0
3,1.170000e+11,1.170000e+11,1.170000e+11,1.180000e+11,1.110000e+11,61,6,8
4,1.220000e+11,1.170000e+11,1.170000e+11,1.170000e+11,1.110000e+11,61,6,0
...,...,...,...,...,...,...,...,...
31899,1.170000e+11,1.170000e+11,1.200000e+11,1.200000e+11,1.200000e+11,99,9,38217
31900,1.220000e+11,1.170000e+11,1.200000e+11,1.200000e+11,1.200000e+11,99,9,30918
31901,1.170000e+11,1.170000e+11,1.200000e+11,1.200000e+11,1.200000e+11,99,9,2503142
31902,1.220000e+11,1.170000e+11,1.200000e+11,1.200000e+11,1.200000e+11,99,9,233
31903,1.170000e+11,1.170000e+11,1.200000e+11,1.200000e+11,1.200000e+11,99,9,19104

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31904 entries, 0 to 31903
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Lv0     31904 non-null  int64
 1   Lv1     31904 non-null  int64
 2   Lv2     31904 non-null  int64
 3   Lv3     31904 non-null  int64
 4   Lv4     31904 non-null  int64
 5   LvPK    31904 non-null  int64
 6   Size    31904 non-null  int64
 7   LvPK_2  31904 non-null  int64
dtypes: int64(8)
memory usage: 1.9 MB

In [11]:
def create_node_mapping(df, columns):
    unique_nodes = set()
    for col in df[columns].columns: 
        unique_nodes.update(df[col].unique())
    return {node: i for i, node in enumerate(sorted(unique_nodes))}

# Create the node mapping
columns = ['Lv4', 'LvPK', 'LvPK_2']
node_mapping = create_node_mapping(df, columns)

In [25]:
sources = []
targets = []
values = []
colors = []  # For link colors

target_node = 9  # Specify your target node here
highlight_color = 'rgba(255, 0, 0, 0.5)'  # Highlight color for the paths leading to the target node
default_color = 'rgba(0, 0, 0, 0.1)'  # Default color for other paths

In [26]:
def row_leads_to_target(row, target_node):
    return target_node in row[2:-1].values  # Check if target node is in the steps

In [27]:
for _, row in df.iterrows():
    row_highlighted = row_leads_to_target(row, target_node)
    for i in range(2, len(df.columns) - 2):
        source = node_mapping[row[i]]
        target = node_mapping[row[i + 1]]
        value = row['Size']
        sources.append(source)
        targets.append(target)
        values.append(value)
        colors.append(highlight_color if row_highlighted else default_color)

# Create the Sankey diagram
fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        line=dict(color="black", width=0.5),
        label=list(node_mapping.keys())
    ),
    link=dict(
        source=sources,
        target=targets,
        value=values,
        color=colors  # Add custom colors
    )
)])

fig.update_layout(title_text="Multi-Level Sankey Diagram with Highlighted Paths", font_size=10)
fig.show()

KeyError: 117401000000